/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jfrmAdicionarForumComunidade.java
 *
 * Created on 05/11/2011, 12:15:54
 */
package br.ufc.si.poo.orkut.gui;

import br.ufc.si.poo.orkut.beans.comunidade.Comunidade;
import br.ufc.si.poo.orkut.beans.comunidade.ComunidadePrivada;
import br.ufc.si.poo.orkut.beans.forum.Forum;
import br.ufc.si.poo.orkut.beans.usuario.Usuario;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author italoney
 */
public class jfrmAdicionarForumComunidade extends javax.swing.JFrame {

    //<editor-fold defaultstate="collapsed" desc="Membros privados">
    private Map<String, Comunidade> comunidades;
    private Map<String, Usuario> usuarios;
    private Map<String, Forum> foruns;
    //</editor-fold> 

    /** Creates new form jfrmAdicionarForumComunidade */
    public jfrmAdicionarForumComunidade() {
        initComponents();
    }

    /**
     * @author italoney
     * Contrutor para inicializar propriedades
     * @param comunidades comunidades disponiveis
     * @param usuarios usuários disponiveis
     * @param foruns foruns disponiveis
     */
    public jfrmAdicionarForumComunidade(Map<String, Comunidade> comunidades, Map<String, Usuario> usuarios, Map<String, Forum> foruns) {
        initComponents();
        inicializarCampos();
        this.comunidades = comunidades;
        this.usuarios = usuarios;
        this.foruns = foruns;

        preencherCombComunidades();
        preencherListaForuns();
        //preencherListaRelacionamento();
        jcmbComunidade.setSelectedIndex(0);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistRelacionamento = new javax.swing.JList();
        btnAdicionar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlistForum = new javax.swing.JList();
        jcmbComunidade = new javax.swing.JComboBox();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relacionamento Comunidade x Forum", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 14))); // NOI18N

        jScrollPane1.setViewportView(jlistRelacionamento);

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/ufc/si/poo/orkut/gui/img/adicionar.png"))); // NOI18N
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jlistForum.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "jlistForum" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlistForum);

        jcmbComunidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "jcmbComunidade" }));
        jcmbComunidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbComunidadeItemStateChanged(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcmbComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnCancelar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jcmbComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-475)/2, (screenSize.height-358)/2, 475, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbComunidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbComunidadeItemStateChanged
        preencherListaRelacionamento();
    }//GEN-LAST:event_jcmbComunidadeItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        jfrmPrincipal m = new jfrmPrincipal();
        m.atualizarListas(comunidades, usuarios, foruns);
        this.dispose();
}//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        Comunidade c = (Comunidade) jcmbComunidade.getSelectedItem();
        if (c instanceof ComunidadePrivada) {
            ComunidadePrivada cp = (ComunidadePrivada) this.comunidades.get(c.getTitulo());
            if (jlistForum.getSelectedValues().length >= 1) {
                for (Object obj : jlistForum.getSelectedValues()) {
                    Forum f = (Forum) obj;
                    if (cp.contemForum(f)) {
                        JOptionPane.showMessageDialog(null, "O forum: "
                                + f.getTitulo() + " já esta na comunidade", "Atenção",
                                JOptionPane.WARNING_MESSAGE);
                    } else {
                        cp.adicionarForum(f);
                        this.comunidades.put(cp.getTitulo(), c);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecione no mínimo um forum", "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Essa comunidade não pode ter foruns",
                    "Erro", JOptionPane.WARNING_MESSAGE);

        }
        preencherListaRelacionamento();
}//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        jfrmPrincipal m = new jfrmPrincipal();
        m.atualizarListas(comunidades, usuarios, foruns);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jfrmAdicionarForumComunidade().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jcmbComunidade;
    private javax.swing.JList jlistForum;
    private javax.swing.JList jlistRelacionamento;
    // End of variables declaration//GEN-END:variables

    /**
     * @author italoney
     * Preencher lista de relacionamentos de acordo com a comunidade selecionada.
     */
    private void preencherListaRelacionamento() {
        Comunidade comunidade = (Comunidade) jcmbComunidade.getSelectedItem();
        DefaultListModel dlm = new DefaultListModel();

        if (comunidade != null) {

            if (comunidade instanceof ComunidadePrivada) {
                ComunidadePrivada cp = (ComunidadePrivada) this.comunidades.get(comunidade.getTitulo());
                for (Forum forum : cp.getForuns()) {
                    dlm.addElement(forum);
                }

                jlistRelacionamento.setModel(dlm);
            } else {
//                JOptionPane.showMessageDialog(null, "Essa comunidade não pode ter foruns",
//                        "Atenção", JOptionPane.WARNING_MESSAGE);
                dlm = new DefaultListModel();
                jlistRelacionamento.setModel(dlm);
            }
        }
    }

    /**
     * @author italoney
     * Preencher combobox com as comunidades disponiveis para relacionamento.
     */
    private void preencherCombComunidades() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();

        for (Comunidade comunidade : this.comunidades.values()) {
            dcbm.addElement(comunidade);
        }

        jcmbComunidade.setModel(dcbm);
    }

    /**
     * @author italoney
     * Preencher lista de foruns disponiveis para relacionamento.
     */
    private void preencherListaForuns() {
        DefaultListModel dlm = new DefaultListModel();
        for (Forum forum : this.foruns.values()) {
            dlm.addElement(forum);
        }

        jlistForum.setModel(dlm);
    }

    /**
     * @author italoney
     * Inicializar campos do focmulário
     */
    private void inicializarCampos() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        DefaultListModel dlm = new DefaultListModel();
        jlistForum.setModel(dlm);
        //jlistRelacionamento.setModel(dlm);
        jcmbComunidade.setModel(dcbm);

    }
}
